version: "3.9"

services:
  app:
    build:
      context: "."
      dockerfile: ./docker/python/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - database
      - redis

  database:
    container_name: database
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_NAME}

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
    volumes:
      - redis_data:/data

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}?sslmode=disable
    depends_on:
      - database

volumes:
  postgres_data:
  redis_data: